### ISSUE TITLE
Why is CSS scoped?

### ISSUE THREAD

**Issue by McNetic** [mattzollinhofer/vue-typeahead-bootstrap#10]
Any idea why the css is scoped? I would much prefer it not to be scoped...

**Comment by mattzollinhofer** [comment]
Scoping the CSS is pretty standard for Vue components. I wouldn't want the styles from this component to leak out and unintentionally affect the site that it's used within. This component is specifically trying to follow bootstrap customs and allow your configuration of bootstrap to provide the style needed.

Hope that helps!
