### ISSUE TITLE
Missing dist folder

### ISSUE THREAD

**Issue by JordonFieldPro** [mattzollinhofer/vue-typeahead-bootstrap#101]
Latest releases (2.7.0 and greater) are missing the dist folder when using npm.

**Comment by mattzollinhofer** [comment]
Yeah, I see what you're saying. I believe the package I just pushed: `2.7.3` has this `dist` folder. I seem to have not fully grasped the correct way to package up the component. Something is still off in balancing the package size and making the needed files available. I think this is fixed (for now?) with `2.7.3`.

Re-open if it's still an issue.
