### ISSUE TITLE
On item select, it incorrectly fires @input="lookupUser"

### ISSUE THREAD

**Issue by ruralcoder** [mattzollinhofer/vue-typeahead-bootstrap#103]
The event `@input="lookupUser"` is incorrectly fired upon an `item selection` which in turn fires one unnecessary network request.

**Comment by mattzollinhofer** [comment]
I just took at look at this and am not sure where you're seeing this. `lookupUser` is only in the docs code, which honestly isn't perfect. If there's an extra network request in the docs, I can live with that.

If this component is making an extra network request every time a selection is made, I'm interested in looking into that.

If you have an additional information I'd appreciate it.

**Comment by mattzollinhofer** [comment]
Closing for now to keep the issues list up-to-date. Happy to reopen if additional information is provided.
