### ISSUE TITLE
`serializer` validation fails, and throws ton of errors in console.

### ISSUE THREAD

**Issue by m-demydiuk** [mattzollinhofer/vue-typeahead-bootstrap#110]
Hi, there is a bug, that also was in initial repository.

If set `serializer` property it always throws console warn `Invalid prop: custom validator check failed for prop "serializer".`
I think the best way is to remove serializer validator at all.
```js
serializer: {
      type: Function,
      default: (d) => d,
    },
```

**Comment by mattzollinhofer** [comment]
Honestly, I'm not super confident in the `validator` part, but it seems like it's working for the examples (http://localhost:8080/vue-typeahead-bootstrap-docs/examples/examples.html#api-example). I don't see any console errors when using it. Maybe the example can help clarify the issue?

**Comment by m-demydiuk** [comment]
@mattzollinhofer do you use `Vue.config.silent` option? Maybe you don't see these warnings because warnings are disabled themselves. It becomes pretty annoying for our development team, so would be great if you can help us with this :)
