### ISSUE TITLE
There are a way to behave like an input select, on set focus a list with all options would show

### ISSUE THREAD

**Issue by graterol-oswaldo** [mattzollinhofer/vue-typeahead-bootstrap#119]
It's like set "minMatchingChars" to zero and when on set focus a list with all options is showing. There are a way to do this ? 

P.D. I'm speaker native spanish and I'm still learning english language. So, I'm sorry for any spelling or grammatical mistake

**Comment by JordonFieldPro** [comment]
I think you are looking for the "showOnFocus" prop.  https://mattzollinhofer.github.io/vue-typeahead-bootstrap-docs/guide/reference.html#props

**Comment by graterol-oswaldo** [comment]
Hi @JordonFieldPro, thank so much,  the "showOnFocus" prop is exactly i was looking for. I did read the reference section but i think overlooking it.
