### ISSUE TITLE
SSR Support (nuxt)

### ISSUE THREAD

**Issue by drone-ah** [mattzollinhofer/vue-typeahead-bootstrap#19]
Hi,

I am using this component in a nuxt application and I have to disable SSR to get this component to work (i.e. use `mode: 'client'` and `<client-only>...</client-only>`.

While this works fine for the most part, there is a small delay before the component is rendered. It would be good to have SSR support to make it a bit more efficient :D 

Best Wishes,

Shri

**Comment by mattzollinhofer** [comment]
Hey @drone-ah, I'm sorry (embarrassed?) to say I'm not too familiar (other than that it exists) with nuxt and I definitely don't know how to go about supporting SSR. 

We're still working through a lot of fundamental features and issues with this component, so we won't be looking to support specifics like this at this time. Honestly, for now, I'll be trying to keep the scope of this project as limited as is reasonable to ensure that we can support it for a while to come.

I'm open to hearing a more thorough proposal about what changes would be necessary to support SSR and nuxt, but I wanted to give you some clarity about my current intentions. If you do want to have that conversation, please open a PR (no code necessary unless you want to) to go into more details and specifics about the changes you'd propose. Then we can have a fuller discussion.

**Comment by pdpotter** [comment]
I got the component working in a nuxt application by configuring the vue-typeahead-bootstrap component to be [transpiled in nuxt.config.js](https://nuxtjs.org/api/configuration-build/#transpile):
```
{
  build: {
    transpile: [
      ({ isServer }) => 'vue-typeahead-bootstrap'
    ]
  }
}
```
