### ISSUE TITLE
Labeler action broken for forks

### ISSUE THREAD

**Issue by RossmacD** [mattzollinhofer/vue-typeahead-bootstrap#22]
The automatic Labeler seems to be broken - 
Gives error `HttpError: Resource not accessible by integration` on every pull request from a fork

Reading up on it it seems like it will not work on forks of the repository as these does not have write access:
https://github.com/actions/labeler/issues/12

**Comment by RossmacD** [comment]
@BozoJim think you worked on this, any ideas or am i misunderstanding how it should work?

**Comment by BozoJim** [comment]
Hmm. I hadn't seen those issues, but it looks pretty broken short of giving forks write access, which I suspect @mattzollinhofer isn't keen on doing.

We can delete `.github/labeler.yml` and `.github/workflows/label.yml`. This was thrown in as a "what if we do this" without much thought into the specifics. I'm happy to remove the labeler it as it seems to break the benefits of using github actions.

If someone else doesn't get to it, I'll get that change done this evening.

**Comment by mattzollinhofer** [comment]
Yeah, thanks for the thoughts @BozoJim and @RossmacD. I just reverted that commit, it was an interesting experiment, may try it again later :-)

**Comment by mattzollinhofer** [comment]
I think this issue is resolved now, if not feel free to mention me to re-look at it!
