### ISSUE TITLE
Work Through Parent PRs

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/vue-typeahead-bootstrap#23]
Evaluate PRs from parent (https://github.com/alexurquhart/vue-bootstrap-typeahead/pulls) for inclusion in this component.

The outcome of this issue will be:
-  All PRs are commented on by one of this projects maintainers
- PRs that we decide to move forward with and are complete are merged in.
- PRs that are good ideas, but not yet complete are duplicated/moved/etc here so that we can continue to discuss and work through them.

**Comment by RossmacD** [comment]
Some quick notes I made to show progress on PRs based on the comments in them:

- [x] [**Add keyboard navigation:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/10)
merged

- [x] [**Preset Value:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/21)
merged

- [x] [**Add keyboard navigation+autoscroll:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/13)
merged

- [x] [**Disable Sorting:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/24)
meged

- [ ] [**Additional fix for replace on null:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/32)
probably merged?

- [ ] [**Disable option:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/34)
Needs to be looked at

- [ ] [**Update input value without the need for refs:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/38)
Needs to be looked at

- [ ] [**Set the default of value to empty string:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/41)
needs to be looked at - possibly fixed

- [x] [**Add keyboard navigation:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/44)
merged

- [x] [**Add showAll option:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/45)
merged

- [x] [**ShowOnFocus:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/47)
merged

- [ ] [**Required prop:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/48)
Needs looking at

- [ ] [**Update scoped slot suggestion template to use Vue 2.60+ syntax.:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/51)
Needs to be looked at

- [x] [**Preset Value:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/53)
merged

- [x] [**Added a rawResults flag:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/54)
merged

- [x] [**Added 'No results found' on emtpy matchedItems:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/55)
Working, needs to be looked at
(First thoughts: Might need to be optional / would be nice to be a slot?)

- [x] [**Initial value not being preserved for v-model**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/59)
merged

- [ ] [**Loading:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/65)
Needs to be looked at, author will update/fix if asked

- [ ] [**Added diacritcs attribute to make input diacritics insensitive: (Normalise special accents - e.g à gets turned to a)**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/66)
Needs looking at

- [x] [**ShowOnFocus/ShowAllResults:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/68)
merged

- [x] [**ShowOnFocus:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/70)
merged

- [ ] [**Prevent chrome autocomplete:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/72)
Seems to be working already? needs to be looked at

- [x] [**Disable regex items matching - showAllResults:**](https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/74)
merged

**Comment by mattzollinhofer** [comment]
this is good enough, plenty of work to be done on this repo. Thanks @RossmacD for helping organize this!
