### ISSUE TITLE
Sever "forked from" Relationship

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/vue-typeahead-bootstrap#24]
I reached out to GitHub support staff to see if they were able to reach Alex, the owner of this parent repository and they were not. They are not able to transfer the repo or anything like that (for obvious reasons). The only thing they suggested that we consider was to sever the relationship to the parent repository. If we request it, GitHub support will be happy to do that.

I'm thinking about whether that's a good idea or not. The goal of reviving this repo is to continue the good work that was done at the parent repository. But, because we've been unable to reach the maintainer, there will be confusion between this repo and the now legacy, historic, repo. I want to keep credit for the original work while reducing confusion. I think that when you discover a new tool to use and see the "forked from" label at the top of GitHub you confidence is diminished slightly and you're caused to wonder which repo to use. I'd like to remove that question from people's minds.

Since we've been unable to reach the owner and there has been confusion (https://github.com/alexurquhart/vue-bootstrap-typeahead/issues/60), I leaning towards severing the tie back to the original repo. 

Any thoughts? A simple thumbsup or thumbsdown is fine or share your thoughts in more detail.

**Comment by RossmacD** [comment]
I think severing is a good idea, I would even think about going as far as a name change, just to clarify that it is a different package and to avoid confusion in documentation, maybe vue typeahead bootstrap 2 or something? This could give full credit to Alex for the first, reduce confusion and show that this is the actively maintained version.

For example if you google vue typeahead bootstrap documentation the original alexurqhart project will come up and given there is such a subtle difference in the name you might not notice.

Credit for the initial work can be given at the top of the readme.

That’s my thoughts on it anyway

**Comment by mattzollinhofer** [comment]
Yeah, your name change is definitely valid. It's unfortunate that naming is the first thing you have to do. I went back and forth at the time between this name and "vue-bootstrap-typeahead-2". I honestly just have a strong preference against the 2 version, so I couldn't do it. To justify it to myself, I tell myself that you'd still have google ranking issues, but what can you do :-).

I think eventually this project will "win" the rank battle, it'll just take time to show activity vs inactivity. It's not the end of the world.

**Comment by mattzollinhofer** [comment]
Another point on the "sever" side is that creating a PR in this repo always tries to go back to the original one by default. That's just annoying.

**Comment by mattzollinhofer** [comment]
@BozoJim @alpharahl any thoughts on this? Unless you have other thoughts, I think I'm going to move forward with severing.

**Comment by BozoJim** [comment]
Yeah, I think the biggest benefit of severing is the PR confusion. It's an extra step to ensure you're opening against the right repo, which by default, you're not. You have my vote there. It's unfortunate that we have to do something so drastic to achieve that.

I'm happy to hear Github was responsive when you asked them about it. it sounds like they implied they did a bit of homework trying to track down @alexurquhart.

I wouldn't worry too much about the search results thing. I suspect that'll work itself out after a while.

**Comment by alpharahl** [comment]
I tend to agree with the arguments posted above. I don't have any real reason not to do it and see benefits to doing so

**Comment by mattzollinhofer** [comment]
I've requested this repo to be detached (severed). Will close this when I get confirmation.

**Comment by mattzollinhofer** [comment]
All done, closing!
