### ISSUE TITLE
List items searched

### ISSUE THREAD

**Issue by JustinSabanal** [mattzollinhofer/vue-typeahead-bootstrap#32]
I want to add a picture in the list searched. How can I edit the list of the items searched?

**Comment by mattzollinhofer** [comment]
We prefer to use this github issue tracker for bugs/features/enhancements that affect groups of our users, not for single user questions. For support like that stackoverflow is a better option, you'll see some questions here: https://stackoverflow.com/search?q=vue+typeahead+bootstrap

If you feel like I've misjudged your request, you're welcome to comment and clarify.

With that said, you can put whatever content you want in the dropdown. Take a look at the README here: https://github.com/mattzollinhofer/vue-typeahead-bootstrap#scoped-slots

**Comment by JustinSabanal** [comment]
I'm sorry because I am just a beginner in using vuejs and find some things here hard at first. Thank you for your reply!
