### ISSUE TITLE
html in `append` & `prepend`

### ISSUE THREAD

**Issue by ttodua** [mattzollinhofer/vue-typeahead-bootstrap#33]
Would be nice if we could add html in prepend/append, not only plain strings.

**Comment by mattzollinhofer** [comment]
Interesting. Could you provide a little more detail about your use case. An example of the code you'd like to be able to use would be helpful to make sure I'm understanding you correctly.

**Comment by ttodua** [comment]
for example, `<faa fa-icon...>` fonts awesome icons

**Comment by BozoJim** [comment]
This has my vote. 👍 
In the meantime, I haven't checked, but I bet you can prepend/append emoji by copy/pasting them. Might be an okay band-aid if you can find a good enough substitue until we can get this implemented.

**Comment by pdpotter** [comment]
Both prepend and append are [defined](https://github.com/mattzollinhofer/vue-typeahead-bootstrap/blob/master/src/components/VueTypeaheadBootstrap.vue#L5-L7) in a [named slot](https://vuejs.org/v2/guide/components-slots.html#Named-Slots), which can be overridden with html. Example:
```
<vue-typeahead-bootstrap
  v-model="input"
  :data="data"
>
    <template v-slot:prepend>
      <span class="input-group-text">
        <em>Prepend</em>&nbsp;using the&nbsp;<strong>slot</strong>
      </span>
    </template>
</vue-typeahead-bootstrap>
```

**Comment by ttodua** [comment]
@pdpotter  thanks! however, while using such "trick" would be good if this will be implemented in repo.

**Comment by mattzollinhofer** [comment]
After re-reading this, I believe that @pdpotter is on the right track. The slots are provided for you to do anything more than simple strings. If you want html in append and prepend, you can use the slots.

I'm going to close this for now, if we're missing something, please feel free to clarify and provide a more detailed example.

Thanks for adding clarify @pdpotter, really appreciate it!

**Comment by ttodua** [comment]
matt, pitty it was closed. all the point here was simplicity for adding just 1 single option for the prepend/append to accept the html. the proposed SLOTS just is an extra workload and complexity addition to code. i could have achieved the goal with jquery too, but that was the reason i wished there was a simple property (i.e. acceptHtml or whatever) which could make things very simple so we could remember that property when we want to prepend html. 
now we have to write the extra slots code blocks for very simple goals..
well, you are the owner, as you wish. tnx. would be glad if anyone makes PR for this.
