### ISSUE TITLE
Update the npm package

### ISSUE THREAD

**Issue by MrDenexi** [mattzollinhofer/vue-typeahead-bootstrap#36]
Hi,

I got some issues with the keyboard navigation using the package from npm. Looking at the merged PR's most of these issues are already solved. (thanks for that!)

Could you update the npm package so it's easy to get the latest version?

Thanks in advance.

**Comment by mattzollinhofer** [comment]
Yep, thanks for following along. Trying to make some progress tonight, and get something to bpm by the weekend 😀
