### ISSUE TITLE
event.preventDefault() for Enter key

### ISSUE THREAD

**Issue by cwiegleb** [mattzollinhofer/vue-typeahead-bootstrap#37]
Thank you so much that you took over the work from [alexurquhart](https://github.com/alexurquhart/vue-bootstrap-typeahead) for this npm package. 

### Is your proposal related to a problem?
The arrow keys work well but if I select an item and press `Enter` the event chain starts again. 
It will take over the value in the input field and afterwards it shows the `vue-bootstrap-typeahead-list` again. 

### Describe the solution you'd like
It would be great to stop the event propagation after the `Enter` event

[Fork from  lisandromc/vue-bootstrap-typeahead](https://github.com/lisandromc/vue-bootstrap-typeahead/blob/master/src/components/VueBootstrapTypeahead.vue)

```
handleKeyDown(evt) {
      if (! this.isFocused || this.data.length < 1) return
      switch (evt.code) {
        case 'ArrowUp':
        case 'ArrowDown':
        case 'Enter':
          evt.preventDefault()
          this.$emit('selectionKeyPressed', evt)
          break
      }
    }
```
Cheers
Christian

**Comment by mattzollinhofer** [comment]
Thanks for using the component, we hope we're helping!

A couple of thoughts:

1. There has been a little work done to key press handling recently, would you mind updating to the latest version and letting us know if it still isn't working?
2. If it isn't working, does hooking into the emitted `hit` event work? Something like this (completely untested code):
```
<VueTypeaheadBootstrap 
  ...
  @hit="$event.preventDefault()"
/>
```

**Comment by mattzollinhofer** [comment]
Closing for now to keep the issues list up-to-date. Happy to reopen if additional information is provided.
