### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by mazenchami** [mattzollinhofer/vue-typeahead-bootstrap#40]
Is there a list of the difference between this library and [vue-bootstrap-typeahead](https://github.com/alexurquhart/vue-bootstrap-typeahead)?

**Comment by BozoJim** [comment]
This repo is a continuation of the excellent work that was done on vue-bootstrap-typeahead. As far as any of us can tell, that repo is no longer supported, and has not been for quite some time. We've forked into vue-typeahed-bootstrap and have continued development. We're aware the similar name is a bit of an issue, names are hard.

Please feel free to open issues or pull requests here if you run into any issues.

**Comment by mazenchami** [comment]
thank you @BozoJim. I will transition to this library instead!
