### ISSUE TITLE
Props like inputClass and minMatchingChars not working for me.

### ISSUE THREAD

**Issue by nickerloke** [mattzollinhofer/vue-typeahead-bootstrap#41]
Just checking because I never see this issue reported. Are inputClass and minMatchingChars suppose to work? I cant seems to make it work.

**Comment by mattzollinhofer** [comment]
yes, they are supposed to work and I believe they do -- I'm sorry to hear you're having trouble getting them to work. 

I just added to the docs to show a few more options in use. Check out the custom slot example here: https://mattzollinhofer.github.io/vue-typeahead-bootstrap-docs/examples/examples.html#custom-suggestion-slot

**Comment by nickerloke** [comment]
![Capture 1](https://user-images.githubusercontent.com/65850011/82781375-36c96600-9e8c-11ea-9dea-bb3db75ed3aa.PNG)
![Capture](https://user-images.githubusercontent.com/65850011/82781379-392bc000-9e8c-11ea-8da6-dd6490e720cf.PNG)
Been following the documentation but I can see the minmatchingchars and inputclass attaching to the div instead of the input search.

**Comment by mattzollinhofer** [comment]
I see what you're saying, but I'm not sure what to suggest. The only thing that stands out is that `inputClass` is not expecting an object so maybe that's causing unexpected behavior. If you inspect the docs example I listed you'll see that the class (`special-input-class`) is on the input as you're expecting.

We prefer to use this github issue tracker for bugs/features/enhancements that affect groups of our users, not for single user questions. For support like that stackoverflow is a better option, you'll see some questions here: https://stackoverflow.com/search?q=vue+typeahead+bootstrap

**Comment by nickerloke** [comment]
yeah I get what you mean. I tried inputClass="form-control primary-select parent-width" and its still attaching to the div instead of the input search.
