### ISSUE TITLE
would be nice if you tell people to use this repo instead of alex

### ISSUE THREAD

**Issue by ttodua** [mattzollinhofer/vue-typeahead-bootstrap#42]
as title says, in every pull request or issue there, would be nice to tell people switching to this repo.

**Comment by mattzollinhofer** [comment]
I've done this on many of the issues PRs, but it's not something I'm probably going to be able to keep up with manually. Do you have a suggestion about how to do this?

**Comment by ttodua** [comment]
well, just once in a month, scrolling through of those topics and posting
or
opening a topic under ISSUES (and making 1 pull request) with titles including several eye-catching [symbols](https://www.vertex42.com/ExcelTips/unicode-symbols.html) in the title like:

⛔❗❎💡 This project is abandonded! Development is continued in XYZ repo!!🌟🌟

**Comment by mattzollinhofer** [comment]
Yeah, feel free to do that. I'm comfortable with out efforts to communicate about this.
