### ISSUE TITLE
IE 11 Click Handling Fails

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/vue-typeahead-bootstrap#48]
The `click` is not registered when using IE 11 (and 10 I believe).

**Comment by BozoJim** [comment]
I was working on it today. I found a partial fix but it introduced a new bug making the form not close when it loses focus. I'll hopefully find a resolution tomorrow.

**Comment by mattzollinhofer** [comment]
Cool. I spoke briefly with @alpharahl about it too -- he might have a thought or two for you, but I know he hadn't really gotten into it yet.

**Comment by rmuraliananth** [comment]
@mattzollinhofer @BozoJim any temporary workaround for this issue?

**Comment by mattzollinhofer** [comment]
Not that I know of. This is our highest priority right now though. Hoping to figure it out soon, but open to ideas! 😀

**Comment by alpharahl** [comment]
This is addressed by: #53

**Comment by mattzollinhofer** [comment]
@rmuraliananth I just pushed `v2.2.0` to npm: https://www.npmjs.com/package/vue-typeahead-bootstrap hopefully that fixes the issue!

**Comment by rmuraliananth** [comment]
> @rmuraliananth I just pushed `v2.2.0` to npm: https://www.npmjs.com/package/vue-typeahead-bootstrap hopefully that fixes the issue!

Great & Thanks,  It works in IE

**Comment by rmuraliananth** [comment]
@mattzollinhofer  - Below scenario does not work in IE

- If the focus is NOT in the drop-down values and try to select the element then it does not select values & model did not get update

- But If you try with tab key to focus the drop-down values & select the element then value get selected, also model gets updated

Tested with both version 2.2.0 & 2.3.0 

Reference : your example https://mattzollinhofer.github.io/vue-typeahead-bootstrap-docs/examples/examples.html#basic

**Comment by mattzollinhofer** [comment]
Really helpful information @rmuraliananth, thanks!

We’ll take a look soon.

**Comment by mattzollinhofer** [comment]
@alpharahl, can you take a look when you have a minute?

**Comment by alpharahl** [comment]
Thanks for pointing this out @rmuraliananth . You made me realize I forgot to update the docs for IE. (that's now done) However, your comment implies we havn't quite fixed all of it. I'm struggling to reproduce the issues you're finding though. Can you post a more detailed step by step process to reproduce this error?

**Comment by rmuraliananth** [comment]
@alpharahl 

**Steps:** Reference to Basic Example

1. Enter "uni" in input field
2. Drop-down values shows  "United Kingdom" &"United States" 
3. Select "United States" drop-down value using Mouse

**Expected:** "United States" drop-down value will be selected and input value should updated to "United States" 
**Actual:** The selected "United States" drop-down value did not get selected & did not updated into input field

**Comment by NathanH-ABN** [comment]
I am using the suggestion slot to make the results into links, but clicking on them does not work even though they are links...is this related to this issue?

**Comment by mattzollinhofer** [comment]
@alpharahl, any thoughts on this? Are you seeing the same behavior that @rmuraliananth is seeing in IE?

**Comment by bryn-newell** [comment]
Just wanted to say thank you for picking up and continuing to maintain this project as well as finding the blur/focusout IE fix! I was going crazy trying to figure that out for an adapted version of typeahead I'm using in a project. Finding that someone else had already sorted out the solution was such a relief! And that seems to be all that was needed for the fix in my case.

**Comment by alpharahl** [comment]
I'm unable to reproduce this. By visiting the docs on IE: (using the latest version) the typeahead works as expected.

**Comment by mattzollinhofer** [comment]
I'm going to close this for now. Mixed results from different people. If more folks have this issue they'll hopefully find their way to this issue and help add some more clarity. Sorry we couldn't figure it out @rmuraliananth!

**Comment by t11k** [comment]
I have similar issue as @rmuraliananth . In IE11 clicking any option on the list closes the list but does not update the input value. Here is a short screen recording showing this behaviour: https://streamable.com/9idufk

**Comment by rmuraliananth** [comment]
> I have similar issue as @rmuraliananth . In IE11 clicking any option on the list closes the list but does not update the input value. Here is a short screen recording showing this behaviour: https://streamable.com/9idufk

Thanks @t11k  for more providing more detail.

FYI -> If use tab key, the dropdown option is selected  but it does not work mouse click event

**Comment by mattzollinhofer** [comment]
I'm not sure how to resolve this, but thanks for the video, that definitely helps. Maybe we can take a look soon @alpharahl, seems related to the blur issue that we've gone back and forth on.

**Comment by alpharahl** [comment]
We added an attirbute `ieCloseFix` in a previous release. If you're having issues with IE you can include that attribute `<vue-typeahead-bootstrap ... ieCloseFix ... />`. This should fix the bug you're seeing

**Comment by mattzollinhofer** [comment]
I just pushed `2.5.6` which defaults the use of the IE close fix, which was in introduced in `2.5.5-beta`, to true. I _think_ this should address the IE issues. 

The fix isn't perfect as it's just ham-fistedly working around a timing issue by slowing down intentionally :-(. I'm very open to a better solution, but this will hopefully improve things a bit.

**Comment by mattzollinhofer** [comment]
Closing for now as I think this should help. We can re-open again later if necessary.
