### ISSUE TITLE
Value not preserved on route changed

### ISSUE THREAD

**Issue by lalits2002** [mattzollinhofer/vue-typeahead-bootstrap#5]
I have used v-model directive and I can see value is set into my store which I am populating again on mounted callback but that value is not populating in the typeahead text box.

**Comment by mattzollinhofer** [comment]
Have you tried the newest version?

I merged in functionality that may fix this, but I'm not entirely sure I understand your issue.

You can try the new functionality here: https://github.com/mattzollinhofer/vue-typeahead-bootstrap (note that the name changed).

If that doesn't help I'm afraid I'll need some more details to understand.

Hope this helps anyone who needs this functionality going forward!
