### ISSUE TITLE
Capturing @keyup.enter?

### ISSUE THREAD

**Issue by AbrahamBrookes** [mattzollinhofer/vue-typeahead-bootstrap#59]
I am trying to capture the `@keyup.enter` event so that I can handle users entering new data when there are no suggestions available (I am using this for a tag creator component - select from existing tags or create a new tag if there is none existing). I see in the code that the `@keyup.enter` event is being passed straight up with `$emit` but I can't seem to catch that event when using this component. Am I doing this wrong?

   
		<vue-typeahead-bootstrap
			:data="allTags"
			v-model="searchStr"
			:serializer="item => item.tag"
			@hit="selectTag"
			placeholder="Start typing..."
			ref="searchInp"
			@keyup.enter="handleKeyup(param)"
		></vue-typeahead-bootstrap>

**Comment by mattzollinhofer** [comment]
I see your problem, I just tried locally and don't receive that event either. The `hit` event and `input` event we're emitting seem to work as expected, but it seems like re-emitting `keyup.enter` doesn't work. I could add another `enter` event and throw that, but I'd be curious if anyone had any thoughts first.

@pdpotter or @BARNZ: you've had some helpful thoughts recently. Is there something about vue that I'm missing here? @BozoJim?

**Comment by BARNZ** [comment]
Can't easily check right now now, but maybe you're just missing the .native modifier?

**Comment by pdpotter** [comment]
I thought I was able to capture the `keyup.enter` event before, but when checking now, I realized this was not the case.

I created a pull request with a fix (emitting `keyup` on all `keyup` events on the input element). The complete event is emitted instead of only the value, otherwise it isn't possible to listen on e.g., `keyup.enter`.

**Comment by mattzollinhofer** [comment]
Thanks for the thought @BARNZ and thanks for the PR @pdpotter!

@AbrahamBrookes you should be good to go, check out the new version. If you need an example, this one shows off the new `keyup` event: https://mattzollinhofer.github.io/vue-typeahead-bootstrap-docs/examples/examples.html#prepend-append
