### ISSUE TITLE
Optimize Dist File Size

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/vue-typeahead-bootstrap#63]
Our distributed js could be quite a bit smaller. The inclusion of lodash is definitely impacting us. I did a quick test of simply deleting this lodash import ([link](https://github.com/mattzollinhofer/vue-typeahead-bootstrap/blob/master/src/components/VueTypeaheadBootstrapList.vue#L23)):
`import {clone, includes, isEmpty, reject, reverse, findIndex} from 'lodash'`

It resulted in a 31kb file, down from 102kb.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/444766/87255460-db156500-c458-11ea-85fa-683e30363423.png">

Two options:

1. Simply replace those specific uses of lodash with vanilla javascript. This is totally doable and I'd be very happy with this outcome. 
2. We could also look into improving the compression and/or only including the specific lodash functions we use. Supposedly the entire lodash compressed js is only 4kb. If that's true, there's no good reason for us to see 60+kb show up when we use it.

**Comment by wb2you** [comment]
My final distribution file came to 43kb, for whatever reason?

**Comment by mattzollinhofer** [comment]
Thanks for the data point, that’s odd. Not sure what to make of it, but either way, this thing should be smaller 😆

**Comment by ttodua** [comment]
This PR should do that : https://github.com/mattzollinhofer/vue-typeahead-bootstrap/pull/82

it uses the modular import, instead of importing whole `lodash`.

**Comment by mattzollinhofer** [comment]
Resolved by #84.

Let me know if this can get better.
