### ISSUE TITLE
Does not close when clicking outside the suggestion list

### ISSUE THREAD

**Issue by jonalxh** [mattzollinhofer/vue-typeahead-bootstrap#65]
Hi, I'm working with your component but there is a strange behavior when I hover an item of the suggestion list with arrow keys and click on the backdrop (outside), because it must close the list with or without selection, but the hovered item loses focus and the list keep showing.

The expected behavior is it to autoselect the hovered/focused item and closes the list, but it'll be ok if just closes the suggestions.

How to solve/handle this?

Thanks for your time.

**Comment by mattzollinhofer** [comment]
This sounds like a bug. Which browser are you seeing this in?

**Comment by mattzollinhofer** [comment]
Also, I just released a fix for some issues with arrow keys. @jonalxh, can you give it a try again with the newest (2.5.1) release to see if that helps?

**Comment by mattzollinhofer** [comment]
Closing for now, to keep the issues list up-to-date. Happy to reopen if additional information is provided.

**Comment by jonalxh** [comment]
Stille happening the same behavior in latests version, excuse me, I've been very busy. I'm using Google Chrome Version 86.0.4240.111 (Official Build) (64-bit).

**Comment by mattzollinhofer** [comment]
Oh, I understand what you're saying now. Yeah, that's definitely a bug. 

### Repro

1. https://mattzollinhofer.github.io/vue-typeahead-bootstrap-docs/
1. click into country selection
1. down arrow once
1. mouse click off control (anywhere on the `body`)

component list stays open but should have closed.

**Comment by mattzollinhofer** [comment]
@alpharahl, you've looked at the blur behavior a little bit. Anything obvious stand out to you?

don't forget, to run locally: `vuepress dev docs`

**Comment by mattzollinhofer** [comment]
I'm starting to think this has been a bug since the beginning (at least for a long time). I reverted back to tag at `2.0.0` and I'm still seeing the issue there. Hoping I can figure out a good fix for it.

**Comment by mattzollinhofer** [comment]
This is fixed in `2.8.0`. Give that a shot @jonalxh

**Comment by jonalxh** [comment]
Hi @mattzollinhofer good job. Is the version already available?
