### ISSUE TITLE
Select first result on enter

### ISSUE THREAD

**Issue by WoLpH** [mattzollinhofer/vue-typeahead-bootstrap#67]
It would be very useful if an "Enter" would result in the first result being selected

**Comment by mattzollinhofer** [comment]
I agree that this would be a good option. There are definitely cases where I would not want that behavior though. This isn't super high priority, but I would definitely work with someone if they submitted a PR for this.

**Comment by MLDMoritz** [comment]
When there is only one result, and you hit enter, it's the common thing to select. I support this.

**Comment by jakubdostal** [comment]
@mattzollinhofer Is there anything I can do to help get PR #111 reviewed? We're hoping to use this typeahead for a project and this is the last missing bit for feature parity with the component we are trying to replace.
Thank you!

**Comment by mattzollinhofer** [comment]
> Is there anything I can do to help

Gentle nagging like this is unfortunately your best bet 😂. 

I’m hoping to take a look at issues and PRs this weekend and next week. Keep an eye out.

**Comment by mattzollinhofer** [comment]
I just released `2.9.0` to resolve this issue. Big thank you to @jakubdostal for the work!!!
