### ISSUE TITLE
Add aria-live to dropdown section

### ISSUE THREAD

**Issue by alpharahl** [mattzollinhofer/vue-typeahead-bootstrap#72]
In order to improve our footprint with regards to accessibility, we need to add an aria-live region to the dropdown so screen readers announce to users when changes have been made. We might also want to consider using the `vue-announcer` package here.

**Comment by mattzollinhofer** [comment]
I definitely want to provide default support for `aria-live`, but I hesitate require clients to use additional packages if they aren't absolutely necessary. Does `vue-announcer` provide substantial benefit over?

**Comment by mattzollinhofer** [comment]
After a bunch of reading, it appears that aria-live isn't a common way to implement this. PR #78 is my best effort at this so far. More details in 

e2ff6caff19971278e7a2cdc7e3bcc6544e1f74a give a more detailed message.
