### ISSUE TITLE
Preselect value from api source

### ISSUE THREAD

**Issue by m-demydiuk** [mattzollinhofer/vue-typeahead-bootstrap#74]
Hi,

I have edit form, and typeahead control loads data from API. So when the edit form is opened, control should preload data from api and show item with a predefined value. Any suggestions on how to achieve this?

Thanks!

**Comment by mattzollinhofer** [comment]
Sorry, I don't have much suggestion for you. I think preloading (getting the data from the API) is up to the application not this component and so will be application specific.
