### ISSUE TITLE
How can it work in below scenarios?

### ISSUE THREAD

**Issue by lalits2002** [mattzollinhofer/vue-typeahead-bootstrap#8]
It should ignore white spaces like if I search for Robinwood and there is record "robin wood" it should display

It should consider ë, è, é,  ê as only e when searching. Pls help

**Comment by mattzollinhofer** [comment]
Thanks for your thoughts and interest. I'm definitely hoping to support additional characters you mentioned. I know there is at least one outstanding PR about that. There are still a number of issues and PRs to work through though so you may have to be patient on it.

I do not expect to support ignoring white space at this time. I could see providing a configuration option that would allow you to provide a custom matcher to meet specific needs like that. But that may be a ways off.
