### ISSUE TITLE
Key up and down functionality does not work in IE 11

### ISSUE THREAD

**Issue by dtw8hn** [mattzollinhofer/vue-typeahead-bootstrap#80]
Even in the example provided here, https://mattzollinhofer.github.io/vue-typeahead-bootstrap-docs/examples/examples.html#basic I've unable to use the key-up key-down, or even select an option in the dropdown. Is ie 11 support on the radar for this project?

**Comment by AnotherUsernameAvailable** [comment]
Hi, not working for me on Brave and Firefox with 2.5.4 version !

**Comment by mattzollinhofer** [comment]
I just pulled in the code from 2.5.5-beta. This is probably related to #48 as well. Closing for now. Chime in if IE support is still not working.
