### ISSUE TITLE
Too heavy(big) module in size. Can't be it minimized?

### ISSUE THREAD

**Issue by ttodua** [mattzollinhofer/vue-typeahead-bootstrap#83]
I accidentally noticed, that this plugin adds around 250kb to the build size (our whole project is around 1200kb). 

![Image](https://i.imgur.com/kaExdoC.png)
_(btw, we used `webpack-bundle-analyzer` )_

So, this is dramatically big size.  What is more strange, it also adds around `230kb` (marked with second red arrow) `vue/dist` folder into bundle. 
Shortly, `webpack-bundle-analyzer` shows everything perfectly.  the configuration of this plugin is broken. (  I saw that it created `/node_modules/` inside its folder while it's actually under node_modeles itself, adding up 250kb +230kb to the bundle).
 
(p.s. we will be also glad if you confimr this pull request: https://github.com/mattzollinhofer/vue-typeahead-bootstrap/pull/82  . for some reasons it doesnt pass GitHub barriers, i dont know well...) 
thanks

(what i observed, there are some plugins, like `vue-lazyload` or others, which's  package.json doesnt contain "vue" in dependencies. I donno if related. `resize-observer` module seemd to add also slight [35kb] which was not ideal though.. )

**Comment by ttodua** [comment]
@wb2you @alpharahl  maybe you have some ideas?

**Comment by mattzollinhofer** [comment]
Thanks for the explanation and the PR. It should be merged now. Hopefully we can continue to do better, feel free to improve this more.

Resolved by #84.
