### ISSUE TITLE
List lodash as dependency

### ISSUE THREAD

**Issue by KjetilHaaheim** [mattzollinhofer/vue-typeahead-bootstrap#86]
Hi!

Please update required dependencies to include lodash, it has now broken our production QA-server. It has worked fine before, I do see import changes in latest commits.

Module not found: Error: Can't resolve 'lodash/clone' in '/var/lib/jenkins/jobs/xx/workspace/node_modules/vue-typeahead-bootstrap/src/components'

ERROR in ./node_modules/vue-typeahead-bootstrap/src/components/VueTypeaheadBootstrapList.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-typeahead-bootstrap/src/components/VueTypeaheadBootstrapList.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'lodash/findIndex' in '/var/lib/jenkins/jobs/gds-qa-maven/workspace/node_modules/vue-typeahead-bootstrap/src/components'

Etc etc.

**Comment by mattzollinhofer** [comment]
Hm, well, we definitely did just make a change to lodash imports to reduce the size of the component. 

I just cut a PR #87 and pushed a beta release to npm. Take a look and see if that resolves your issue? Any thoughts @ttodua?

**Comment by ttodua** [comment]
@mattzollinhofer  might be the lodash should be in dependencies, however, the goal which was achieved, will still be on place i think. (i mean the modular import of lodash).  So, having lodash in dependencies shouldnt affect the way it is being used (modular) in components, and the dist size might remain same. Am I right?

**Comment by mattzollinhofer** [comment]
> having lodash in dependencies shouldnt affect the way it is being used (modular) in components, and the dist size might remain same

Yeah, that’s what I was thinking, we’ll see. 

> woudln't npm i lodash (and then re-running the task ) fix the problem

I think it would, but I don’t think it’s expected to run npm i manually before running tests on ci.

**Comment by KjetilHaaheim** [comment]
> @KjetilHaaheim woudln't `npm i lodash` (and then re-running the task ) fix the problem, before Matt updates the repo?

Absolutely :-). Just felt it should be in package.json as it was not listed as a dependency, thus not being installed by CD/CI.

Dist size would absolutely be the same, it would just let npm know that it also needs it, and grab it whilst installing lodash. It should be put in `dependencies`, as you require it in production as well. `devDependencies` are not required after running a build. 

Vue probably have lodash as a dev-dependency if they use it for tooling. In the same sense, node & npm is by definition itself dev-dependencies, but is not included in the final build.

**Comment by mattzollinhofer** [comment]
@KjetilHaaheim, I forgot to update this issue, but I think this should be resolved as of v2.5.5. Closing for now, let me know if I missed something.
