### ISSUE TITLE
How can we fetch results from the api?

### ISSUE THREAD

**Issue by lalits2002** [mattzollinhofer/vue-typeahead-bootstrap#9]
How can we fetch results from the api?

**Comment by lalits2002** [comment]
I have found how we can do with API but there is one issue. I want populate the result same as return by my api but its filtering by its own.

for example: If I am searching abc and my api returning xyz it should be available to select. Please let me know how can we do that?

**Comment by mattzollinhofer** [comment]
If I understand you correctly, you want to use the `showAllResults` feature that was recently added. Take a look at the [README](showAllResults) for the description and usage details.

I hope that helps!

**Comment by mattzollinhofer** [comment]
I closed this more quickly than I intended originally, but it's been quiet since my last comment so I'm going to consider this issue resolved. Feel free to comment if there's something else going on.
