### ISSUE TITLE
CDN implementation

### ISSUE THREAD

**Issue by jag2kn** [mattzollinhofer/vue-typeahead-bootstrap#90]
This document explaint how to deploy libraries into cdn:

https://medium.com/@gaute.meek/how-to-publish-a-js-library-to-npm-and-cdn-9d0bf9b48e11

**Comment by mattzollinhofer** [comment]
I believe this component is available from a CDN unpkg (https://unpkg.com/vue-typeahead-bootstrap). 

Closing this issue because I think the need is already met and the issue isn't very descriptive. If you have something else in mind please provide some additional information.
